### PR TITLE
CMake: misc fixes, using new infra modules

### PR DESCRIPTION
**Pull request by redtide**
~~Draft: requires cycfi/infra#19, then change the infra submodule branch to master.~~
Testing other changes...

### CODE REVIEW

**Comment by redtide** [comment]
@djowel I'm also working on an Elements PR and I see we have infra included 2 times there: by both Elements and Artist; can we remove the Elements submodule and use the Artist one?

**Comment by djowel** [comment]
> @djowel I'm also working on an Elements PR and I see we have infra included 2 times there: by both Elements and Artist; can we remove the Elements submodule and use the Artist one?

Ah makes sense!

**Comment by djowel** [comment]
@redtide I think we should first target a feature branch and then merge to develop once stable. There are clients expecting a stable develop branch.

**Comment by redtide** [comment]
Looking at Elements in particular (but also a bit in Artist) after Infra changes there are a lot of things to simplify and also to fix, it's quite a mess (duplicate scripts, different variable names and other little things around), so from my POV it's not about a feature but adapt and fix.

Making a middle way change it's difficult to me, because there are cascading changes to apply that impacts Artist which in turn impacts to Elements, I have no idea how to make this without a straightforward, direct change.

In brief it's not "something nice to have" but "something required". OTOH who is going to test a feature branch which has nothing new to see?

**Comment by djowel** [comment]
> Making a middle way change it's difficult to me, because there are cascading changes to apply that impacts Artist which in turn impacts to Elements, I have no idea how to make this without a straightforward, direct change.

Feature branches are also tested, so I do not know what you mean. I think we are not in the same page. I always test on feature branches for potentially large changes, in multiple repositories. I just make feature branches on all relevant repositories and point each to its dependencies.

> In brief it's not "something nice to have" but "something required". OTOH who is going to test a feature branch which has nothing new to see? I'm not even changing a line of c++ code, it's all about CMake.

You cannot guarantee that. CMake changes can also cause disruption. Let's do it in a feature branch please. And please let's not "fix" what is not broken. I am OK for an incremental upgrade, but not for a wholesale change. 

No argument, please ;-)

**Comment by djowel** [comment]
> feature branch which has nothing new to see

The binaries. Those are not vetted yet.

**Pull request closed without merging**
