### PR TITLE
Copied axis point and rect methods over from elements:master branch

### PR DESCRIPTION
**Pull request by bruno-j-nicoletti**

### CODE REVIEW

**Comment by bruno-j-nicoletti** [comment]
Anything else you need me to do?

**Comment by djowel** [comment]
> Anything else you need me to do?

I think this is all for Artist. The next thing is to port element's `skia_2024` branch to this one based on new tile implementation from element's `master`.

**Comment by djowel** [comment]
> > Anything else you need me to do?
> 
> I think this is all for Artist. The next thing is to port element's `skia_2024` branch to this one based on new tile implementation from element's `master`.

Done.

**Comment by djowel** [comment]
Done. Now your code is in element's `master` and `skia_2024`, both merged two-way.

**Comment by bruno-j-nicoletti** [comment]
Great!

**Pull request merged**
